global:
  marketplace-ami: false
  owner: mgbuddy@gmail.com
  qsname: quickstart-puppet
  s3bucket: g2-quickstart-templates
  regions:
    - us-east-1
  reporting: true
tests:
  test1:
    regions:
      - us-east-1
    parameter_input: Calavera-QuickStart.json
    template_file: Calavera-QuickStart.template
